#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Nov  6 16:22:08 2016

@author: white08057
"""

import os 
#full_path = os.path.realpath('moduletest.py')

os.chdir('/Users/white08057/GitHub/ggplotExamples/')
os.chdir(os.path.dirname(sys.argv[0]))

import os
__file__ = 'moduletest.py'
abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(dname)


'''
print("Path at terminal when executing this file")
print(os.getcwd() + "\n")

print("This file path, relative to os.getcwd()")
print(__file__ + "\n")

print("This file full path (following symlinks)")
full_path = os.path.realpath(__file__)
print(full_path + "\n")

print("This file directory and name")
path, filename = os.path.split(full_path)
print(path + ' --> ' + filename + "\n")

print("This file directory only")
print(os.path.dirname(full_path))
'''

### mainprogam.py
### IMPORTS ANOTHER MODULE
import moduletest