#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Nov  2 21:43:40 2016

@author: white08057
"""
#import the packages i need to write my program
#installation for ggplot : cmd: pip install -U ggplot
#or conda install -c conda-forge ggplot
#documentation: https://pypi.python.org/pypi/ggplot/

from ggplot import * 
import matplotlib.pyplot as plt

import seaborn as sns
import pandas as pd
import numpy as np
import math as math
import time
import string


'''Options:
    The Options (in ~Descending Order of Subjective Complexity)
    
    matplotlib -r(for really customized visually plots)
    pandas - mostly for dataframes (plots are slightly more easy than matlablib)
    seaborn - makes hard things (in matlabplot) easy, also good for statistical transformation
    yhat’s ggplot - similar to R
    Altair = similar to ggplot (pythons version essentially)
    
    
    
'''

'''
LINES AND DOTS
'''

import string
import random

foo = ['A','B','C']
length = 20

def id_generator(size, chars):
    return ''.join(random.choice(chars) for _ in range(size))

new_list=id_generator(length,foo)

letters =[]
letters += new_list
print(letters)


'''time for some random dates'''
file = '/Users/white08057/GitHub/ggplot2/data-raw/economics.csv'

df = pd.read_csv(file) #, header=None,index_col='datetime',parse_dates = {'datetime': [2,3]}, date_parser=lambda x: pd.datetime.strptime(x, '%Y %m'))  #'%Y %m %d %H'
df.info()
#function to convertthe datetime index to be a column in the pandas dataframe in order to plot correctly when switching from wide to long format.

def dateConvert(df):
  df['Date'] = df.index
  df.reset_index(drop=True)
  return df


new_df= df['date'].astype('datetime64[ns]')






# First, make some random data
x = np.random.normal(loc = 5, scale = 2, size = length)
y = x + np.random.normal(loc = 0, scale = 2, size = length)
 
# Make these into a pandas dataframe. I do this because
# more often than not, I read in a pandas dataframe, so this
# shows how to use a pandas dataframe to plot in ggplot
testData = pd.DataFrame( {"letter":letters, 'x':x, 'y':y} )
# it looks just like a dataframe from R
print(testData)

ts = testData #want to sort the data alphabetically

# MATPLOTLIB
fig, ax = plt.subplots(1, 1,
                       figsize=(7.5, 5))
 
for k in ts.letter.unique():
    tmp = ts[ts.letter == k]
    ax.plot(tmp.x, tmp.y, label=k)
 
ax.set(xlabel='Date',
       ylabel='Value',
       title='Random Timeseries')    
 
ax.legend(loc=2)
fig.autofmt_xdate()



# SEABORN
g = sns.FacetGrid(ts, hue='letter', size=5, aspect=1.5)
g.map(plt.plot, 'x', 'y').add_legend()
g.ax.set(xlabel='Date',
         ylabel='Value',
         title='Random Timeseries')
g.fig.autofmt_xdate()


#Notes: passing in "Kind" for hue will give you several different lines
'''
# SEABORN
g = sns.FacetGrid(ts, hue='kind', size=5, aspect=1.5)
g.map(plt.plot, 'dt', 'value').add_legend()
g.ax.set(xlabel='Date',
         ylabel='Value',
         title='Random Timeseries')
g.fig.autofmt_xdate()
'''









'''
    




print(df.head())
df.info()
plt2 = ggplot(aes(x = 'date', y='pop'),data = df) +\
        geom_line(color = 'purple', size =1.5, alpha = 0.75) +\
        stat_smooth(color = 'blue',size =2.0, span = 0.15) +\
        scale_x_date(labels = date_format("%m/%d/%y")) +\
        xlab('Year') + ylab('Head of Cattle Slaughtered') +\
        ggtitle('Beef Consumption over Time') #+\
        #theme_seaborn() #cant get this to work just yet
print(plt2)
    

'plotting 2 lines'
plt3 = ggplot(aes(x= 'date'),df) +\
          geom_line(aes(y = 'pop', colour = "blue")) +\
          geom_line(aes(y = 'unemploy', colour = "green"))

print(plt3)

'plotting 2 lines'
plt4 = ggplot(aes(x= 'date'),df) +\
          geom_line(aes(y = 'pop', colour = "blue")) +\
          geom_line(aes(y = 'unemploy', colour = "green"))
          
print(plt4)



'''

''' now that we can plot, lets explore other options:
    
https://dansaber.wordpress.com/2016/10/02/a-dramatic-tour-through-pythons-data-visualization-landscape-including-ggplot-and-altair/



df_new = dateConvert(df_first)
#pd.to_datetime(df_first['date'])

df_new.info()
#Df_convert = dateConvert(Df)

#qplot(df.pce)

#data = pd.melt(Df_convert, id_vars='date').dropna() # Here is the method I use to format the data in the long format. Please note the use of 'Date' as the id_vars.


pv_plot = ggplot(df, aes('date','pop')) + \
    geom_point(color='black') 
print(pv_plot)



'''